awdr/ch2/demo/config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'

  get 'say/goodbye'

end

awdr/ch2/demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

awdr/ch2/demo/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	@time = Time.now
  end

  def goodbye
  end
end

awdr/ch2/demo/app/helpers/application_helper.rb
module ApplicationHelper
end

awdr/ch2/demo/app/helpers/say_helper.rb
module SayHelper
end

awdr/ch2/demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

awdr/ch2/demo/app/views/say/goodbye.html.erb
<h1>Goodbye!</h1>
<p>It was nice having you here</p>

awdr/ch2/demo/app/views/say/hello.html.erb
<h1>Hello From Rails!</h1>
<p>
	It is now <%= @time %>
	Say <a href="/say/goodbye">Goodbye</a>!
</p>
<p>
	Time to say
	<%= link_to "Goodbye", say_goodbye_path %>!
</p>
<p>
	<%= 1+2 %>
</p>
<p>
	<%= 0.5.hour.from_now.localtime %>
</p>
<p>
	<%= "cow" + "boy" %>
</p>
<p>
	<%= @files = Dir.glob('*') %>
</p>
<p>
	<% for file in @files %>
	<p>file name is: <%= file %></p>
	<% end %>
</p>